/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package simulacion.grafica;

import Civilizacion.vg;
import javax.swing.JOptionPane;

/**
 *
 * @author gaby
 */
public class Edificios extends javax.swing.JFrame {

    /**
     * Creates new form Edificios
     */
    public aldeaGRAP copia;
    public Edificios(aldeaGRAP obj) {
        copia = obj;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButtonElixir = new javax.swing.JButton();
        jButtonMina = new javax.swing.JButton();
        jButtonChoza = new javax.swing.JButton();
        jButtonCuartel = new javax.swing.JButton();
        jButtonTorre = new javax.swing.JButton();
        jButtonMortero = new javax.swing.JButton();
        jButtonCampamento = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButtonCañon = new javax.swing.JButton();

        jButton4.setText("jButton4");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setText("Edificios Disponibles");

        jLabel2.setText("Recolector de Elixir (150 ORO)");

        jLabel4.setText("Mina de Oro (150 ELIXIR)");

        jLabel6.setText("Choza de Constructor (200 ELIXIR)");

        jLabel7.setText("Campamento (250 ELIXIR)");

        jLabel8.setText("Cuartel (200 ELIXIR)");

        jLabel9.setText("Cañon (250 ORO)");

        jLabel10.setText("Torre de Arqueras (1000 ORO)");

        jLabel12.setText("Mortero (8000 ORO)");

        jButtonElixir.setText("Comprar");
        jButtonElixir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonElixirActionPerformed(evt);
            }
        });

        jButtonMina.setText("Comprar");
        jButtonMina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinaActionPerformed(evt);
            }
        });

        jButtonChoza.setText("Comprar");
        jButtonChoza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChozaActionPerformed(evt);
            }
        });

        jButtonCuartel.setText("Comprar");
        jButtonCuartel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCuartelActionPerformed(evt);
            }
        });

        jButtonTorre.setText("Comprar");
        jButtonTorre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTorreActionPerformed(evt);
            }
        });

        jButtonMortero.setText("Comprar");
        jButtonMortero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMorteroActionPerformed(evt);
            }
        });

        jButtonCampamento.setText("Comprar");
        jButtonCampamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCampamentoActionPerformed(evt);
            }
        });

        jButton13.setText("Volver a la Aldea");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButtonCañon.setText("Comprar");
        jButtonCañon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCañonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jButton13)
                .addContainerGap(253, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonCañon))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                                .addComponent(jButtonMina))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                                .addComponent(jButtonElixir))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                                .addComponent(jButtonChoza))
                            .addComponent(jLabel10)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonCuartel)
                                        .addComponent(jButtonCampamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButtonMortero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonTorre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addGap(142, 142, 142))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMina)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonElixir)
                    .addComponent(jLabel2))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonChoza)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCuartel)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCañon)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTorre)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMortero)
                    .addComponent(jLabel12))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jButton13))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCampamento)
                            .addComponent(jLabel7))))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
       
        this.setVisible(false);
    }//GEN-LAST:event_jButton13ActionPerformed
    
private void jButtonElixirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonElixirActionPerformed
    copia.ComprarEdificio(vg.RECOLECTOR);
    System.out.println(copia.aldea.oro);
    if(copia.aldea.oro<150.0){
     JOptionPane.showMessageDialog(this, "Necesita 150 de oro para comprarlo", "ERROR", JOptionPane.ERROR_MESSAGE);
    }else{
        JOptionPane.showMessageDialog(this, "Ha empezado a construir un recolector de elixir", "", JOptionPane.WARNING_MESSAGE);
    }
     
}//GEN-LAST:event_jButtonElixirActionPerformed

private void jButtonMinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinaActionPerformed
    copia.ComprarEdificio(vg.MINA);
     if(copia.aldea.elixir<150.0){
     JOptionPane.showMessageDialog(this, "Necesita 150 de elixir para comprarlo", "ERROR", JOptionPane.ERROR_MESSAGE);
    }else{
     JOptionPane.showMessageDialog(this, "Ha empezado a construir una mina de oro", "", JOptionPane.WARNING_MESSAGE);
 }    
}//GEN-LAST:event_jButtonMinaActionPerformed

private void jButtonChozaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChozaActionPerformed
    copia.ComprarEdificio(vg.CHOZA);
    
      if(copia.aldea.elixir<200.0){
     JOptionPane.showMessageDialog(this, "Necesita 200 de elixir para comprarlo", "ERROR", JOptionPane.ERROR_MESSAGE);
    }else{
     JOptionPane.showMessageDialog(this, "Ha empezado a construir una choza de constructor", "", JOptionPane.WARNING_MESSAGE);
}//GEN-LAST:event_jButtonChozaActionPerformed
} 
private void jButtonCuartelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCuartelActionPerformed
    copia.ComprarEdificio(vg.CUARTEL);
    if(copia.aldea.elixir<200.0){
     JOptionPane.showMessageDialog(this, "Necesita 200 de elixir para comprarlo", "ERROR", JOptionPane.ERROR_MESSAGE);
    }else{
    JOptionPane.showMessageDialog(this, "Ha empezado a construir un cuartel", "", JOptionPane.WARNING_MESSAGE);
}//GEN-LAST:event_jButtonCuartelActionPerformed
}  
private void jButtonCañonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCañonActionPerformed
    copia.ComprarEdificio(vg.CAÑON);
    
     if(copia.aldea.oro<250.0){
     JOptionPane.showMessageDialog(this, "Necesita 250 de oro para comprarlo", "ERROR", JOptionPane.ERROR_MESSAGE);
    }else{
     JOptionPane.showMessageDialog(this, "Ha empezado a construir un cañon", "", JOptionPane.WARNING_MESSAGE);
     }
}//GEN-LAST:event_jButtonCañonActionPerformed

private void jButtonTorreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTorreActionPerformed
    copia.ComprarEdificio(vg.TORRE);
     if(copia.aldea.oro<1000.0){
     JOptionPane.showMessageDialog(this, "Necesita 1000 de oro para comprarlo", "ERROR", JOptionPane.ERROR_MESSAGE);
    }else{
     JOptionPane.showMessageDialog(this, "Ha empezado a construir una torre de arqueras", "", JOptionPane.WARNING_MESSAGE);
     }
}//GEN-LAST:event_jButtonTorreActionPerformed

private void jButtonMorteroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMorteroActionPerformed
    copia.ComprarEdificio(vg.MORTERO);
    
    if(copia.aldea.oro<8000.0){
     JOptionPane.showMessageDialog(this, "Necesita 8000 de oro para comprarlo", "ERROR", JOptionPane.ERROR_MESSAGE);
    }else{
     JOptionPane.showMessageDialog(this, "Ha empezado a construir un mortero", "", JOptionPane.WARNING_MESSAGE);
    }
}//GEN-LAST:event_jButtonMorteroActionPerformed

private void jButtonCampamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCampamentoActionPerformed
    copia.ComprarEdificio(vg.CAMPAMENTO);
     if(copia.aldea.elixir<250.0){
     JOptionPane.showMessageDialog(this, "Necesita 250 de elixir para comprarlo", "ERROR", JOptionPane.ERROR_MESSAGE);
    }else{
     JOptionPane.showMessageDialog(this, "Ha empezado a construir un campamento", "", JOptionPane.WARNING_MESSAGE);
     }
}//GEN-LAST:event_jButtonCampamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonCampamento;
    private javax.swing.JButton jButtonCañon;
    private javax.swing.JButton jButtonChoza;
    private javax.swing.JButton jButtonCuartel;
    private javax.swing.JButton jButtonElixir;
    private javax.swing.JButton jButtonMina;
    private javax.swing.JButton jButtonMortero;
    private javax.swing.JButton jButtonTorre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
